"""add all tables for recipeapi

Revision ID: 1f1df57042dd
Revises: c044f9c1e34b
Create Date: 2024-01-05 09:36:15.243677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1df57042dd'
down_revision: Union[str, None] = 'c044f9c1e34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
